spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_NAME}

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 120MB

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}
server:
  port: 8085

